include $(GNUSTEP_MAKEFILES)/common.make
include GNUmakefile.preamble
LIBRARY_NAME = libblockoperation
PACKAGE_NAME = libblockoperation0
PACKAGE_VERSION = 0.1
VERSION = 0.1
libblockoperation_OBJC_FILES = NSBlockOperation.m NSOperationQueue+BlockOperation.m
libblockoperation_HEADER_FILES_INSTALL_DIR = blockOperation
libblockoperation_HEADER_FILES = NSBlockOperation.h NSOperationQueue+BlockOperation.h
include $(GNUSTEP_MAKEFILES)/library.make
