include $(GNUSTEP_MAKEFILES)/common.make
include GNUmakefile.preamble
LIBRARY_NAME = liborderedSet
PACKAGE_NAME=liborderedset
VERSION=0.1
liborderedSet_OBJC_FILES = NSOrderedSet.m NSMutableOrderedSet.m
liborderedSet_HEADER_FILES_INSTALL_DIR = orderedSet
liborderedSet_HEADER_FILES = NSOrderedSet.h NSMutableOrderedSet.h
include $(GNUSTEP_MAKEFILES)/library.make
