ADDITIONAL_LDFLAGS = -Xlinker 
ADDITIONAL_LIB_DIRS = -L /usr/lib -L /usr/local/lib
ADDITIONAL_OBJC_LIBS = -lgnustep-base -ldispatch
ADDITIONAL_GUI_LIBS = -lgnustep-gui
ADDITIONAL_OBJCFLAGS += -fconstant-string-class=NSConstantString
ADDITIONAL_OBJCFLAGS += -DGNUSTEP
ADDITIONAL_OBJCFLAGS += -fblocks
#ADDITIONAL_OBJCFLAGS += -fobjc-runtime=gnustep-1.7
#ADDITIONAL_OBJCFLAGS += -v
