include $(GNUSTEP_MAKEFILES)/common.make
include GNUmakefile.preamble
LIBRARY_NAME = liborderedset
PACKAGE_NAME = liborderedset0
PACKAGE_VERSION = 0.1
VERSION = 0.1
liborderedset_OBJC_FILES = NSOrderedSet.m NSMutableOrderedSet.m
liborderedset_HEADER_FILES_INSTALL_DIR = orderedSet
liborderedset_HEADER_FILES = NSOrderedSet.h NSMutableOrderedSet.h
include $(GNUSTEP_MAKEFILES)/library.make
